spring:
  application:
    name: multiple-databases-spring-data-jpa
  config:
    import: optional:file:.env[.properties]

  jpa:
    # enable logging of SQL statements.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # Create the schema and destroy previous data.
    hibernate:
      ddl-auto: create
    # disable anti pattern OSIV (Open Session in View)
    open-in-view: false

#  datasource:
#    url: jdbc:mysql://${DB_MYSQL_HOSTNAME}:${DB_MYSQL_PORT}/${DB_MYSQL_DBNAME}
#    username: ${DB_MYSQL_USER}
#    password: ${DB_MYSQL_PASSWORD}
#    driver-class-name: ${DB_MYSQL_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}

  datasource:
    mysql:
      url: jdbc:mysql://${DB_MYSQL_HOSTNAME}:${DB_MYSQL_PORT}/${DB_MYSQL_DBNAME}
      username: ${DB_MYSQL_USER}
      password: ${DB_MYSQL_PASSWORD}
      driver-class-name: ${DB_MYSQL_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
    postgresql:
      url: jdbc:mysql://${DB_MYSQL_HOSTNAME}:${DB_MYSQL_PORT}/${DB_MYSQL_DBNAME}
      username: ${DB_MYSQL_USER}
      password: ${DB_MYSQL_PASSWORD}
      driver-class-name: ${DB_MYSQL_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
    mongo:
      url: jdbc:mysql://${DB_MYSQL_HOSTNAME}:${DB_MYSQL_PORT}/${DB_MYSQL_DBNAME}
      username: ${DB_MYSQL_USER}
      password: ${DB_MYSQL_PASSWORD}
      driver-class-name: ${DB_MYSQL_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}