spring:
  application:
    name: logging

  threads:
    virtual:
      enabled: true

  config:
    import: optional:file:.env[.properties]


webservice:
  client:
    url: https://jsonplaceholder.typicode.com
    path:
      comments:
        findAll: ${HTTP_JSON_PLACEHOLDER_URL_PATH_COMMENTS:comments}
      posts:
        findAll: ${HTTP_JSON_PLACEHOLDER_URL_PATH_POSTS:posts}
        comments:
          findAllByPostId: ${HTTP_JSON_PLACEHOLDER_URL_PATH_POSTS_COMMENTS:posts/{id}/comments}