spring:
  application:
    name: introduction_to_rest_client

  threads:
    virtual:
      enabled: true

  config:
    import: optional:file:.env[.properties]

webservice:
  client:
    url: ${HTTP_JSON_PLACEHOLDER_URL:https://jsonplaceholder.typicode.com}
    path:
      posts:
        findAll: ${HTTP_JSON_PLACEHOLDER_URL_PATH_POSTS:posts}
        byId: ${HTTP_JSON_PLACEHOLDER_URL_PATH_FIND_POST_BY_ID:posts/{postId}}

logging:
  level:
    org.springframework.web.client: DEBUG