spring:
  application:
    name: interceptor

  threads:
    virtual:
      enabled: true
  config:
    import: optional:file:.env[.properties]

webservice:
  #  connectTimeout: 1
  #  readTimeout: 2

  client:
    url: ${HTTP_JSON_PLACEHOLDER_URL:https://jsonplaceholder.typicode.com}
    path:
      posts:
        findAll: ${HTTP_JSON_PLACEHOLDER_URL_PATH_POSTS:posts}
      comments:
        findAll: ${HTTP_JSON_PLACEHOLDER_URL_PATH_COMMENTS:comments}

logging:
  level:
    web: debug
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE