spring:
  application:
    name: application_property_error_configuration

  threads:
    virtual:
      enabled: true

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: TRACE

server:
  error:
    include-message: always
    include-stacktrace: always
    whitelabel:
      enabled: true