spring:
  application:
    name: shutdown_spring_boot_application

  threads:
    virtual:
      enabled: true

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
