spring:
  application:
    name: rabbit_amqp
  config:
    import: optional:file:.env[.properties]

  rabbitmq:
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST}

  threads:
    virtual:
      enabled: true

  main:
    allow-bean-definition-overriding: true

rabbitmq:
  dl:
    queue: dl_queue.dlq
    exchange: dl_exchange
    routing:
      key: dl_routing_key
  queue: message_event_queue
  exchange: message_event_exchange
  routing:
    key: message_event_routing_key
  username: ${RABBITMQ_USERNAME}
  password: ${RABBITMQ_PASSWORD}
  host: ${RABBITMQ_HOST:localhost}
  virtualhost: ${RABBITMQ_VIRTUAL_HOST}
  reply:
    timeout: 5000
  concurrent:
    consumers:
      min: 1
      max: 5