spring:
  application:
    name: annotation_configuration

  threads:
    virtual:
      enabled: true

  cloud:
    openfeign:
      client:
        config:
          openFeignClient:
            connectTimeout: 2000
            readTimeout: 2000
            loggerLevel: full

logging:
  level:
    com.malex.annotation_configuration.webservice: DEBUG

service:
  client:
    url: ${HTTP_BIN_URL:http://httpbin.org}
    path:
      status: ${HTTP_BIN_BASIC_AUTH_PATH_STATUS:status/{status}}