spring:
  application:
    name: shutdown-graceful

  lifecycle:
    timeout-per-shutdown-phase: 1m

server:
  shutdown: graceful

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,shutdown