spring:
  application:
    name: introduction

  threads:
    virtual:
      enabled: true

  config:
    import: optional:file:.env[.properties]

  cloud:
    openfeign:
      client:
        config:
          authOpenFeignWebclient:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
            requestInterceptors: com.malex.inroduction.auth.AuthOpenFeignInterception
          bearerOpenFeignWebclient:
            loggerLevel: full

logging:
  level:
    com.malex.inroduction.auth.AuthOpenFeignWebclient: DEBUG
    com.malex.inroduction.bearer.BearerOpenFeignWebclient: DEBUG

service:
  client:
    user: ${HTTP_BIN_BASIC_AUTH_USER:user}
    password: ${HTTP_BIN_BASIC_AUTH_PASSWORD:passwd}
    url: ${HTTP_BIN_URL:http://httpbin.org}
    path:
      auth: ${HTTP_BIN_BASIC_AUTH_PATH_AUTH:basic-auth}
      bearer: ${HTTP_BIN_BASIC_AUTH_PATH_BEARER:bearer}