spring:
  application:
    name: application_level_configuration

server:
  error:
    #
    # 1. with an always value;
    # includes the stacktrace in both the HTML and the JSON default response
    #
    include-stacktrace: always
    #
    # 2. Spring Boot hides the message field in the response to avoid leaking sensitive information;
    # we can use this property with an always value to enable it
    #
    include-message: always