spring:
  application:
    name: interface_handler_exception_resolver_implementation

  threads:
    virtual:
      enabled: true

  config:
    import: optional:file:.env[.properties]

webclient:
  url: ${HTTP_DUMMY_JSON_URL:https://dummyjson.com}
  path: ${HTTP_DUMMY_JSON_PRODUCTS_PATH:products}

logging:
  level:
    org.springframework.web.servlet: ${APP_SERVICE_SPRING_LOG_LEVEL:DEBUG}

server:
  error:
    include-message: always