spring:
  application:
    name: error_handling

  threads:
    virtual:
      enabled: true

  config:
    import: optional:file:.env[.properties]

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full

logging:
  level:
    com.malex.error_handling.webservice.OpenFeignClientImpl: DEBUG


service:
  client:
    user: ${HTTP_BIN_BASIC_AUTH_USER:user}
    password: ${HTTP_BIN_BASIC_AUTH_PASSWORD:passwd}
    url: ${HTTP_BIN_URL:http://httpbin.org}
    path:
      auth: ${HTTP_BIN_BASIC_AUTH_PATH_AUTH:basic-auth}
      status: ${HTTP_BIN_BASIC_AUTH_PATH_STATUS:status/{status}}