spring:
  application:
    name: error_handling

  threads:
    virtual:
      enabled: true

  config:
    import: optional:file:.env[.properties]

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full

logging:
  level:
    org.springframework.cloud.openfeign.FeignClient: DEBUG