spring:
  application:
    name: properties_file_configuration

  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss

server:
  error:
    #
    # 1. with an always value;
    # includes the stacktrace in both the HTML and the JSON default response
    #
    include-stacktrace: always
    #
    # 2. Spring Boot hides the message field in the response to avoid leaking sensitive information;
    # we can use this property with an always value to enable it
    #
    include-message: always
