spring:
  application:
    name: shutdown

  threads:
    virtual:
      enabled: true



#endpoints:
#  shutdown:
#    enabled: true

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'