spring:
  application:
    name: error_handling

  threads:
    virtual:
      enabled: true

webclient:
  client:
    url: ${HTTP_BIN_URL:http://httpbin.org}
    path:
      status: ${HTTP_BIN_BASIC_AUTH_PATH_STATUS:status/{status}}

server:
  error:
    include-message: always
    include-stacktrace: always
    whitelabel:
      enabled: true

logging:
  level:
    #    web: debug
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE